name: Run Script
on:
  workflow_dispatch:  # This allows manual triggering
  schedule:
    - cron: '23 * * * *'  # Runs at the start of every hour

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Specify the Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 PyRSS2Gen
    - name: Run the script
      run: python AFL_RSS.py  # Replace with your script name
    - name: Commit and push if changes
      run: |
        git config --global user.email "tomjrenk@protonmail.com"
        git config --global user.name "renkt99"
        git commit -am "Update feed"
        git push
